// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm93AyVReVTDq5barde5H6zvd2GDawjqM',
    appId: '1:316921386386:web:7bc66ef51d5ba3b0d15d4b',
    messagingSenderId: '316921386386',
    projectId: 'kodekraken-6969',
    authDomain: 'kodekraken-6969.firebaseapp.com',
    databaseURL: 'https://kodekraken-6969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kodekraken-6969.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9DXIkerTpAj_bR5riUB3w2FwQysCUUYw',
    appId: '1:316921386386:android:ebed6b32180f7fb9d15d4b',
    messagingSenderId: '316921386386',
    projectId: 'kodekraken-6969',
    databaseURL: 'https://kodekraken-6969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kodekraken-6969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBspXpN725IeceB4MIkSnat6W9-Kxfqoic',
    appId: '1:316921386386:ios:45a9efc0d2c1aa23d15d4b',
    messagingSenderId: '316921386386',
    projectId: 'kodekraken-6969',
    databaseURL: 'https://kodekraken-6969-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kodekraken-6969.appspot.com',
    iosClientId: '316921386386-jvcio4ijdpsp5ha94elgj36uq5k02ecr.apps.googleusercontent.com',
    iosBundleId: 'com.example.kodeKraken',
  );
}
